# Generated by Django 3.1.3 on 2020-11-16 17:28

from django.db import migrations
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def load_products_and_customer(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    from django.core.management import call_command
    from django.contrib.auth import get_user_model
    call_command("loaddata", "products")
    call_command("loaddata", "customers")

    users = get_user_model()
    for user in users.objects.all():
        user.set_password("1234")
        user.save()


def reset_data(apps, schema_editor: DatabaseSchemaEditor) -> None:
    product = apps.get_model("store", "Product")
    product.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_products_and_customer, reverse_code=reset_data)
    ]
